[project]
name = "notifications"
version = "0.1.0"
description = "Notifications Department Communication Service"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "confluent-kafka[avro]>=2.3.0",
    "fastavro>=1.9.4",
    "sqlalchemy>=2.0.27",
    "psycopg2-binary>=2.9.9",
    "pytest>=8.0.0",
]

[tool.uv]
managed = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

