[project]
name = "tshirt-enterprise-platform"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "pytest>=8.0.0",
    "sales",
    "shipping",
    "finance",
    "notifications",
    "ops-agent",
    "observability",
    "outbox_daemon",
    "opentelemetry-api>=1.24.0",
    "opentelemetry-sdk>=1.24.0",
    "opentelemetry-exporter-otlp-proto-grpc>=1.24.0",
    "opentelemetry-exporter-otlp-proto-http>=1.24.0",
    "opentelemetry-instrumentation-confluent-kafka>=0.45b0"
]

[tool.uv.sources]
sales = { workspace = true }
shipping = { workspace = true }
finance = { workspace = true }
notifications = { workspace = true }
observability = { workspace = true }
outbox_daemon = { workspace = true }
ops-agent = { workspace = true }

[tool.uv.workspace]
members = [
    "sales",
    "finance",
    "shipping",
    "notifications",
    "observability",
    "outbox_daemon",
    "ops_agent"
]
