[project]
name = "shipping"
version = "0.1.0"
description = "Shipping Department Logistics and Compensation Service"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "observability",
    "langgraph-checkpoint-sqlite>=3.0.1",
    "langgraph>=0.1.0",
    "confluent-kafka[avro,schemaregistry]>=2.3.0",
    "sqlalchemy>=2.0.0",
    "psycopg2-binary>=2.9.0",
    "opentelemetry-api>=1.24.0",
    "opentelemetry-sdk>=1.24.0",
    "opentelemetry-exporter-otlp-proto-http>=1.24.0",
    "opentelemetry-instrumentation-wsgi>=0.45b0"
]

[tool.uv]
managed = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

