apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: explorer-zone
  labels:
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger-container
        image: jaegertracing/all-in-one:1.57
        imagePullPolicy: IfNotPresent
        env:
        - name: COLLECTOR_OTLP_ENABLED
          value: "true"
        ports:
        - containerPort: 16686 # UI Port
        - containerPort: 4318  # OTLP HTTP Port
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
  namespace: explorer-zone
spec:
  selector:
    app: jaeger
  ports:
  - name: otlp-http
    port: 4318
    targetPort: 4318
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-query
  namespace: explorer-zone
spec:
  selector:
    app: jaeger
  ports:
  - name: ui
    port: 16686
    targetPort: 16686
    nodePort: 31686 # Allows opening http://localhost:31686 on your Mac Mini!
  type: NodePort
